/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_samsung_link_stream_service_Live555Native */

#ifndef _Included_Live555Native
#define _Included_Live555Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_samsung_link_stream_service_Live555Native
 * Method:    initialize
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_samsung_link_stream_service_Live555Native_initialize
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_samsung_link_stream_service_Live555Native
 * Method:    loopNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_samsung_link_stream_service_Live555Native_loopNative
  (JNIEnv *, jobject);

/*
 * Class:     com_samsung_link_stream_service_Live555Native
 * Method:    stopNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_samsung_link_stream_service_Live555Native_stopNative
  (JNIEnv *, jobject);

/*
 * Class:     com_samsung_link_stream_service_Live555Native
 * Method:    feedH264Data
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_samsung_link_stream_service_Live555Native_feedH264Data
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_samsung_link_stream_service_Live555Native
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_samsung_link_stream_service_Live555Native_destroy
  (JNIEnv *, jobject);

JNIEXPORT jbyteArray JNICALL Java_com_samsung_link_stream_service_Live555Native_yuvToBuffer
        (JNIEnv *env, jobject, jobject, jobject, jobject, jint, jint, jint, jint, jint, jint, jint, jint);
#ifdef __cplusplus
}
#endif
#endif
